export {default as Dashboard} from './Dashboard'
export {default as Courses} from './Courses'
export {default as Resources} from './Resources'
export {default as Trainee} from './Trainee'
export {default as ExternalTrainingForm} from './ExternalTrainingForm'
export {default as ParticipantsList} from './ParticipantsList'